//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDADMEJORA
    {
        public decimal ID_ACTIVIDADMEJORA { get; set; }
        public string NOMBREMEJORA { get; set; }
        public string DESCRIPCIONMEJORA { get; set; }
    }
}
