//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRASOS
    {
        public decimal ID_ATRASO { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
