//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST
    {
        public decimal ID_CHECK { get; set; }
        public int VISITASTERRENO_ID_VISITA { get; set; }
        public string FIELD01 { get; set; }
        public string FIELD02 { get; set; }
        public string FIELD03 { get; set; }
        public string FIELD04 { get; set; }
        public string FIELD05 { get; set; }
        public string FIELD06 { get; set; }
        public string FIELD07 { get; set; }
        public string FIELD08 { get; set; }
        public string FIELD09 { get; set; }
        public string FIELD10 { get; set; }
        public string FIELD11 { get; set; }
        public string FIELD12 { get; set; }
        public string FIELD13 { get; set; }
        public string FIELD14 { get; set; }
        public string FIELD15 { get; set; }
    
        public virtual VISITASTERRENO VISITASTERRENO { get; set; }
    }
}
