//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALATRASOS
    {
        public decimal ID_ATRASO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string PROFESIONAL_RUT_PROF { get; set; }
    
        public virtual PROFESIONAL PROFESIONAL { get; set; }
    }
}
