//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESIONAL
    {
        public PROFESIONAL()
        {
            this.CONTRATOPROF = new HashSet<CONTRATOPROF>();
            this.SERVICIO = new HashSet<SERVICIO>();
            this.VISITASTERRENO = new HashSet<VISITASTERRENO>();
        }
    
        public string RUT_PROF { get; set; }
        public string ACTIVO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string GENERO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<CONTRATOPROF> CONTRATOPROF { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
        public virtual ICollection<VISITASTERRENO> VISITASTERRENO { get; set; }
    }
}
