//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafeCoreEntities : DbContext
    {
        public SafeCoreEntities()
            : base("name=SafeCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTIVIDADMEJORA> ACTIVIDADMEJORA { get; set; }
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<CONTRATOCLIENT> CONTRATOCLIENT { get; set; }
        public DbSet<CONTRATOPROF> CONTRATOPROF { get; set; }
        public DbSet<PAGOS> PAGOS { get; set; }
        public DbSet<PROFESIONAL> PROFESIONAL { get; set; }
        public DbSet<REPORTEACCIDENTE> REPORTEACCIDENTE { get; set; }
        public DbSet<REPORTECLIENTE> REPORTECLIENTE { get; set; }
        public DbSet<REPORTEGLOBAL> REPORTEGLOBAL { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
        public DbSet<TIPOSOLICITUD> TIPOSOLICITUD { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VISITASTERRENO> VISITASTERRENO { get; set; }
    }
}
