//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SafeCoreEntities : DbContext
    {
        public SafeCoreEntities()
            : base("name=SafeCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTIVIDADMEJORA> ACTIVIDADMEJORA { get; set; }
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<CONTRATOCLIENT> CONTRATOCLIENT { get; set; }
        public DbSet<CONTRATOPROF> CONTRATOPROF { get; set; }
        public DbSet<PAGOS> PAGOS { get; set; }
        public DbSet<PROFESIONAL> PROFESIONAL { get; set; }
        public DbSet<REPORTEACCIDENTE> REPORTEACCIDENTE { get; set; }
        public DbSet<REPORTECLIENTE> REPORTECLIENTE { get; set; }
        public DbSet<REPORTEGLOBAL> REPORTEGLOBAL { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
        public DbSet<TIPOSOLICITUD> TIPOSOLICITUD { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VISITASTERRENO> VISITASTERRENO { get; set; }
        public DbSet<CAPACITACIONES> CAPACITACIONES { get; set; }
        public DbSet<CHECKLIST> CHECKLIST { get; set; }
        public DbSet<HISTORIALATRASOS> HISTORIALATRASOS { get; set; }
    
        public virtual int SP_CREATE_ACTIVIDADMEJORA(string v_NOMBRE, string v_DESCRIPCION, string v_RUTCLIENT)
        {
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_ACTIVIDADMEJORA", v_NOMBREParameter, v_DESCRIPCIONParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_CREATE_CLIENTES(string v_RUT, string v_NOMBRE, string v_DIRECCION, string v_TELEFONO, string v_CORREO, string v_RUBRO)
        {
            var v_RUTParameter = v_RUT != null ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_TELEFONOParameter = v_TELEFONO != null ?
                new ObjectParameter("V_TELEFONO", v_TELEFONO) :
                new ObjectParameter("V_TELEFONO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_RUBROParameter = v_RUBRO != null ?
                new ObjectParameter("V_RUBRO", v_RUBRO) :
                new ObjectParameter("V_RUBRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CLIENTES", v_RUTParameter, v_NOMBREParameter, v_DIRECCIONParameter, v_TELEFONOParameter, v_CORREOParameter, v_RUBROParameter);
        }
    
        public virtual int SP_CREATE_CONTRATOCLIENT(string v_ACTIVO, Nullable<System.DateTime> v_FECHAINICIO, Nullable<System.DateTime> v_FECHATERMINO, string v_RUTCLIENT)
        {
            var v_ACTIVOParameter = v_ACTIVO != null ?
                new ObjectParameter("V_ACTIVO", v_ACTIVO) :
                new ObjectParameter("V_ACTIVO", typeof(string));
    
            var v_FECHAINICIOParameter = v_FECHAINICIO.HasValue ?
                new ObjectParameter("V_FECHAINICIO", v_FECHAINICIO) :
                new ObjectParameter("V_FECHAINICIO", typeof(System.DateTime));
    
            var v_FECHATERMINOParameter = v_FECHATERMINO.HasValue ?
                new ObjectParameter("V_FECHATERMINO", v_FECHATERMINO) :
                new ObjectParameter("V_FECHATERMINO", typeof(System.DateTime));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CONTRATOCLIENT", v_ACTIVOParameter, v_FECHAINICIOParameter, v_FECHATERMINOParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_CREATE_CONTRATOPROF(Nullable<System.DateTime> v_FECHAINICIO, Nullable<System.DateTime> v_FECHATERMINO, string v_HISTORIAL, string v_RUTPROF)
        {
            var v_FECHAINICIOParameter = v_FECHAINICIO.HasValue ?
                new ObjectParameter("V_FECHAINICIO", v_FECHAINICIO) :
                new ObjectParameter("V_FECHAINICIO", typeof(System.DateTime));
    
            var v_FECHATERMINOParameter = v_FECHATERMINO.HasValue ?
                new ObjectParameter("V_FECHATERMINO", v_FECHATERMINO) :
                new ObjectParameter("V_FECHATERMINO", typeof(System.DateTime));
    
            var v_HISTORIALParameter = v_HISTORIAL != null ?
                new ObjectParameter("V_HISTORIAL", v_HISTORIAL) :
                new ObjectParameter("V_HISTORIAL", typeof(string));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CONTRATOPROF", v_FECHAINICIOParameter, v_FECHATERMINOParameter, v_HISTORIALParameter, v_RUTPROFParameter);
        }
    
        public virtual int SP_CREATE_PAGOS(Nullable<System.DateTime> v_FECHA, Nullable<decimal> v_MONTO, string v_RUTCLIENT)
        {
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_MONTOParameter = v_MONTO.HasValue ?
                new ObjectParameter("V_MONTO", v_MONTO) :
                new ObjectParameter("V_MONTO", typeof(decimal));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PAGOS", v_FECHAParameter, v_MONTOParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_CREATE_PROFESIONAL(string v_RUTPROF, string v_ACTIVO, string v_NOMBRE, string v_APELLIDO, string v_GENERO, string v_DIRECCION, string v_TELEFONO, string v_CORREO)
        {
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            var v_ACTIVOParameter = v_ACTIVO != null ?
                new ObjectParameter("V_ACTIVO", v_ACTIVO) :
                new ObjectParameter("V_ACTIVO", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_APELLIDOParameter = v_APELLIDO != null ?
                new ObjectParameter("V_APELLIDO", v_APELLIDO) :
                new ObjectParameter("V_APELLIDO", typeof(string));
    
            var v_GENEROParameter = v_GENERO != null ?
                new ObjectParameter("V_GENERO", v_GENERO) :
                new ObjectParameter("V_GENERO", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_TELEFONOParameter = v_TELEFONO != null ?
                new ObjectParameter("V_TELEFONO", v_TELEFONO) :
                new ObjectParameter("V_TELEFONO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PROFESIONAL", v_RUTPROFParameter, v_ACTIVOParameter, v_NOMBREParameter, v_APELLIDOParameter, v_GENEROParameter, v_DIRECCIONParameter, v_TELEFONOParameter, v_CORREOParameter);
        }
    
        public virtual int SP_CREATE_REPORTEACCIDENTE(string v_RUTCLIENT, Nullable<System.DateTime> v_FECHAACCIDENTE, string v_DESCRIPCION)
        {
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_FECHAACCIDENTEParameter = v_FECHAACCIDENTE.HasValue ?
                new ObjectParameter("V_FECHAACCIDENTE", v_FECHAACCIDENTE) :
                new ObjectParameter("V_FECHAACCIDENTE", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_REPORTEACCIDENTE", v_RUTCLIENTParameter, v_FECHAACCIDENTEParameter, v_DESCRIPCIONParameter);
        }
    
        public virtual int SP_CREATE_REPORTECLIENTE(string v_RUTCLIENT, Nullable<System.DateTime> v_FECHA, string v_DESCRIPCION)
        {
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_REPORTECLIENTE", v_RUTCLIENTParameter, v_FECHAParameter, v_DESCRIPCIONParameter);
        }
    
        public virtual int SP_CREATE_REPORTEGLOBAL(string v_RUTCLIENT, Nullable<System.DateTime> v_FECHA, string v_DESCRIPCION)
        {
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_REPORTEGLOBAL", v_RUTCLIENTParameter, v_FECHAParameter, v_DESCRIPCIONParameter);
        }
    
        public virtual int SP_CREATE_SERVICIO(string v_RUTCLIENT, string v_DESCRIPCION, Nullable<System.DateTime> v_FECHASERVICIO, Nullable<decimal> v_VALOR, string v_RUTPROF)
        {
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_FECHASERVICIOParameter = v_FECHASERVICIO.HasValue ?
                new ObjectParameter("V_FECHASERVICIO", v_FECHASERVICIO) :
                new ObjectParameter("V_FECHASERVICIO", typeof(System.DateTime));
    
            var v_VALORParameter = v_VALOR.HasValue ?
                new ObjectParameter("V_VALOR", v_VALOR) :
                new ObjectParameter("V_VALOR", typeof(decimal));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_SERVICIO", v_RUTCLIENTParameter, v_DESCRIPCIONParameter, v_FECHASERVICIOParameter, v_VALORParameter, v_RUTPROFParameter);
        }
    
        public virtual int SP_CREATE_SOLICITUD(Nullable<System.DateTime> v_FECHA, string v_DESCRIPCION, string v_RUTCLIENT, Nullable<decimal> v_IDTIPOSOLICITUD)
        {
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_IDTIPOSOLICITUDParameter = v_IDTIPOSOLICITUD.HasValue ?
                new ObjectParameter("V_IDTIPOSOLICITUD", v_IDTIPOSOLICITUD) :
                new ObjectParameter("V_IDTIPOSOLICITUD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_SOLICITUD", v_FECHAParameter, v_DESCRIPCIONParameter, v_RUTCLIENTParameter, v_IDTIPOSOLICITUDParameter);
        }
    
        public virtual int SP_CREATE_USUARIOS(string v_NOMBRE, string v_PASS, Nullable<decimal> v_ROLID)
        {
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_PASSParameter = v_PASS != null ?
                new ObjectParameter("V_PASS", v_PASS) :
                new ObjectParameter("V_PASS", typeof(string));
    
            var v_ROLIDParameter = v_ROLID.HasValue ?
                new ObjectParameter("V_ROLID", v_ROLID) :
                new ObjectParameter("V_ROLID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_USUARIOS", v_NOMBREParameter, v_PASSParameter, v_ROLIDParameter);
        }
    
        public virtual int SP_CREATE_VISITASTERRENO(Nullable<System.DateTime> v_FECHAVISITA, string v_RUTPROF, string v_RUTCLIENT)
        {
            var v_FECHAVISITAParameter = v_FECHAVISITA.HasValue ?
                new ObjectParameter("V_FECHAVISITA", v_FECHAVISITA) :
                new ObjectParameter("V_FECHAVISITA", typeof(System.DateTime));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_VISITASTERRENO", v_FECHAVISITAParameter, v_RUTPROFParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_DELETE_CLIENTES(Nullable<decimal> v_RUT)
        {
            var v_RUTParameter = v_RUT.HasValue ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CLIENTES", v_RUTParameter);
        }
    
        public virtual int SP_DELETE_CONTRATOCLIENT(Nullable<decimal> v_IDCONTR)
        {
            var v_IDCONTRParameter = v_IDCONTR.HasValue ?
                new ObjectParameter("V_IDCONTR", v_IDCONTR) :
                new ObjectParameter("V_IDCONTR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CONTRATOCLIENT", v_IDCONTRParameter);
        }
    
        public virtual int SP_DELETE_CONTRATOPROF(Nullable<decimal> v_IDCONTR)
        {
            var v_IDCONTRParameter = v_IDCONTR.HasValue ?
                new ObjectParameter("V_IDCONTR", v_IDCONTR) :
                new ObjectParameter("V_IDCONTR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CONTRATOPROF", v_IDCONTRParameter);
        }
    
        public virtual int SP_DELETE_MEJORA(Nullable<decimal> v_ACTMEJORA)
        {
            var v_ACTMEJORAParameter = v_ACTMEJORA.HasValue ?
                new ObjectParameter("V_ACTMEJORA", v_ACTMEJORA) :
                new ObjectParameter("V_ACTMEJORA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_MEJORA", v_ACTMEJORAParameter);
        }
    
        public virtual int SP_DELETE_PAGOS(Nullable<decimal> v_IDPAGO)
        {
            var v_IDPAGOParameter = v_IDPAGO.HasValue ?
                new ObjectParameter("V_IDPAGO", v_IDPAGO) :
                new ObjectParameter("V_IDPAGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PAGOS", v_IDPAGOParameter);
        }
    
        public virtual int SP_DELETE_PROFESIONAL(Nullable<decimal> v_RUTPROF)
        {
            var v_RUTPROFParameter = v_RUTPROF.HasValue ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PROFESIONAL", v_RUTPROFParameter);
        }
    
        public virtual int SP_DELETE_REPORTEACCIDENTE(Nullable<decimal> v_IDREPORT)
        {
            var v_IDREPORTParameter = v_IDREPORT.HasValue ?
                new ObjectParameter("V_IDREPORT", v_IDREPORT) :
                new ObjectParameter("V_IDREPORT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_REPORTEACCIDENTE", v_IDREPORTParameter);
        }
    
        public virtual int SP_DELETE_REPORTECLIENTE(Nullable<decimal> v_REPORTC)
        {
            var v_REPORTCParameter = v_REPORTC.HasValue ?
                new ObjectParameter("V_REPORTC", v_REPORTC) :
                new ObjectParameter("V_REPORTC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_REPORTECLIENTE", v_REPORTCParameter);
        }
    
        public virtual int SP_DELETE_REPORTEGLOBAL(Nullable<decimal> v_REPORTG)
        {
            var v_REPORTGParameter = v_REPORTG.HasValue ?
                new ObjectParameter("V_REPORTG", v_REPORTG) :
                new ObjectParameter("V_REPORTG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_REPORTEGLOBAL", v_REPORTGParameter);
        }
    
        public virtual int SP_DELETE_SERVICIO(Nullable<decimal> v_IDSERV)
        {
            var v_IDSERVParameter = v_IDSERV.HasValue ?
                new ObjectParameter("V_IDSERV", v_IDSERV) :
                new ObjectParameter("V_IDSERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_SERVICIO", v_IDSERVParameter);
        }
    
        public virtual int SP_DELETE_SOLICITUD(Nullable<decimal> v_IDSOLICITUD)
        {
            var v_IDSOLICITUDParameter = v_IDSOLICITUD.HasValue ?
                new ObjectParameter("V_IDSOLICITUD", v_IDSOLICITUD) :
                new ObjectParameter("V_IDSOLICITUD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_SOLICITUD", v_IDSOLICITUDParameter);
        }
    
        public virtual int SP_DELETE_USUARIOS(Nullable<decimal> v_IDUSER)
        {
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_USUARIOS", v_IDUSERParameter);
        }
    
        public virtual int SP_DELETE_VISITASTERRENO(Nullable<decimal> v_IDVISITA)
        {
            var v_IDVISITAParameter = v_IDVISITA.HasValue ?
                new ObjectParameter("V_IDVISITA", v_IDVISITA) :
                new ObjectParameter("V_IDVISITA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_VISITASTERRENO", v_IDVISITAParameter);
        }
    
        public virtual int SP_UPDATE_CLIENTES(string v_RUT, string v_NOMBRE, string v_DIRECCION, string v_TELEFONO, string v_CORREO, string v_RUBRO)
        {
            var v_RUTParameter = v_RUT != null ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_TELEFONOParameter = v_TELEFONO != null ?
                new ObjectParameter("V_TELEFONO", v_TELEFONO) :
                new ObjectParameter("V_TELEFONO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            var v_RUBROParameter = v_RUBRO != null ?
                new ObjectParameter("V_RUBRO", v_RUBRO) :
                new ObjectParameter("V_RUBRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CLIENTES", v_RUTParameter, v_NOMBREParameter, v_DIRECCIONParameter, v_TELEFONOParameter, v_CORREOParameter, v_RUBROParameter);
        }
    
        public virtual int SP_UPDATE_CONTRATOCLIENT(Nullable<decimal> v_IDCONTR, string v_ACTIVO, Nullable<System.DateTime> v_FECHAINICIO, Nullable<System.DateTime> v_FECHATERMINO, string v_RUTCLIENT)
        {
            var v_IDCONTRParameter = v_IDCONTR.HasValue ?
                new ObjectParameter("V_IDCONTR", v_IDCONTR) :
                new ObjectParameter("V_IDCONTR", typeof(decimal));
    
            var v_ACTIVOParameter = v_ACTIVO != null ?
                new ObjectParameter("V_ACTIVO", v_ACTIVO) :
                new ObjectParameter("V_ACTIVO", typeof(string));
    
            var v_FECHAINICIOParameter = v_FECHAINICIO.HasValue ?
                new ObjectParameter("V_FECHAINICIO", v_FECHAINICIO) :
                new ObjectParameter("V_FECHAINICIO", typeof(System.DateTime));
    
            var v_FECHATERMINOParameter = v_FECHATERMINO.HasValue ?
                new ObjectParameter("V_FECHATERMINO", v_FECHATERMINO) :
                new ObjectParameter("V_FECHATERMINO", typeof(System.DateTime));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CONTRATOCLIENT", v_IDCONTRParameter, v_ACTIVOParameter, v_FECHAINICIOParameter, v_FECHATERMINOParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_UPDATE_CONTRATOPROF(Nullable<decimal> v_IDCONTR, Nullable<System.DateTime> v_FECHAINICIO, Nullable<System.DateTime> v_FECHATERMINO, string v_HISTORIAL, string v_RUTPROF)
        {
            var v_IDCONTRParameter = v_IDCONTR.HasValue ?
                new ObjectParameter("V_IDCONTR", v_IDCONTR) :
                new ObjectParameter("V_IDCONTR", typeof(decimal));
    
            var v_FECHAINICIOParameter = v_FECHAINICIO.HasValue ?
                new ObjectParameter("V_FECHAINICIO", v_FECHAINICIO) :
                new ObjectParameter("V_FECHAINICIO", typeof(System.DateTime));
    
            var v_FECHATERMINOParameter = v_FECHATERMINO.HasValue ?
                new ObjectParameter("V_FECHATERMINO", v_FECHATERMINO) :
                new ObjectParameter("V_FECHATERMINO", typeof(System.DateTime));
    
            var v_HISTORIALParameter = v_HISTORIAL != null ?
                new ObjectParameter("V_HISTORIAL", v_HISTORIAL) :
                new ObjectParameter("V_HISTORIAL", typeof(string));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CONTRATOPROF", v_IDCONTRParameter, v_FECHAINICIOParameter, v_FECHATERMINOParameter, v_HISTORIALParameter, v_RUTPROFParameter);
        }
    
        public virtual int SP_UPDATE_MEJORA(Nullable<decimal> v_ACTIVIDADMEJORA, string v_NOMBREMEJORA, string v_DESCRIPCION, string v_RUTCLIENT)
        {
            var v_ACTIVIDADMEJORAParameter = v_ACTIVIDADMEJORA.HasValue ?
                new ObjectParameter("V_ACTIVIDADMEJORA", v_ACTIVIDADMEJORA) :
                new ObjectParameter("V_ACTIVIDADMEJORA", typeof(decimal));
    
            var v_NOMBREMEJORAParameter = v_NOMBREMEJORA != null ?
                new ObjectParameter("V_NOMBREMEJORA", v_NOMBREMEJORA) :
                new ObjectParameter("V_NOMBREMEJORA", typeof(string));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_MEJORA", v_ACTIVIDADMEJORAParameter, v_NOMBREMEJORAParameter, v_DESCRIPCIONParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_UPDATE_PRODUCTO(Nullable<decimal> v_IDPAGO, Nullable<System.DateTime> v_FECHA, Nullable<decimal> v_MONTO, string v_RUTCLIENT)
        {
            var v_IDPAGOParameter = v_IDPAGO.HasValue ?
                new ObjectParameter("V_IDPAGO", v_IDPAGO) :
                new ObjectParameter("V_IDPAGO", typeof(decimal));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_MONTOParameter = v_MONTO.HasValue ?
                new ObjectParameter("V_MONTO", v_MONTO) :
                new ObjectParameter("V_MONTO", typeof(decimal));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PRODUCTO", v_IDPAGOParameter, v_FECHAParameter, v_MONTOParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_UPDATE_PROFESIONAL(string v_RUTPROF, string v_ACTIVO, string v_NOMBRE, string v_APELLIDO, string v_GENERO, string v_DIRECCION, string v_TELEFONO, string v_CORREO)
        {
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            var v_ACTIVOParameter = v_ACTIVO != null ?
                new ObjectParameter("V_ACTIVO", v_ACTIVO) :
                new ObjectParameter("V_ACTIVO", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_APELLIDOParameter = v_APELLIDO != null ?
                new ObjectParameter("V_APELLIDO", v_APELLIDO) :
                new ObjectParameter("V_APELLIDO", typeof(string));
    
            var v_GENEROParameter = v_GENERO != null ?
                new ObjectParameter("V_GENERO", v_GENERO) :
                new ObjectParameter("V_GENERO", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_TELEFONOParameter = v_TELEFONO != null ?
                new ObjectParameter("V_TELEFONO", v_TELEFONO) :
                new ObjectParameter("V_TELEFONO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PROFESIONAL", v_RUTPROFParameter, v_ACTIVOParameter, v_NOMBREParameter, v_APELLIDOParameter, v_GENEROParameter, v_DIRECCIONParameter, v_TELEFONOParameter, v_CORREOParameter);
        }
    
        public virtual int SP_UPDATE_REPORTEACCIDENTE(Nullable<decimal> v_IDREPORT, string v_RUTCLIENT, Nullable<System.DateTime> v_FECHAACCIDENTE, string v_DESCRIPCION)
        {
            var v_IDREPORTParameter = v_IDREPORT.HasValue ?
                new ObjectParameter("V_IDREPORT", v_IDREPORT) :
                new ObjectParameter("V_IDREPORT", typeof(decimal));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_FECHAACCIDENTEParameter = v_FECHAACCIDENTE.HasValue ?
                new ObjectParameter("V_FECHAACCIDENTE", v_FECHAACCIDENTE) :
                new ObjectParameter("V_FECHAACCIDENTE", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_REPORTEACCIDENTE", v_IDREPORTParameter, v_RUTCLIENTParameter, v_FECHAACCIDENTEParameter, v_DESCRIPCIONParameter);
        }
    
        public virtual int SP_UPDATE_REPORTECLIENTE(Nullable<decimal> v_REPORTC, string v_RUTCLIENT, Nullable<System.DateTime> v_FECHA, string v_DESCRIPCION)
        {
            var v_REPORTCParameter = v_REPORTC.HasValue ?
                new ObjectParameter("V_REPORTC", v_REPORTC) :
                new ObjectParameter("V_REPORTC", typeof(decimal));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_REPORTECLIENTE", v_REPORTCParameter, v_RUTCLIENTParameter, v_FECHAParameter, v_DESCRIPCIONParameter);
        }
    
        public virtual int SP_UPDATE_REPORTEGLOBAL(Nullable<decimal> v_REPORTG, string v_RUTCLIENT, Nullable<System.DateTime> v_FECHA, string v_DESCRIPCION)
        {
            var v_REPORTGParameter = v_REPORTG.HasValue ?
                new ObjectParameter("V_REPORTG", v_REPORTG) :
                new ObjectParameter("V_REPORTG", typeof(decimal));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_REPORTEGLOBAL", v_REPORTGParameter, v_RUTCLIENTParameter, v_FECHAParameter, v_DESCRIPCIONParameter);
        }
    
        public virtual int SP_UPDATE_SERVICIO(Nullable<decimal> v_IDSERV, string v_RUTCLIENT, string v_DESCRIPCION, Nullable<System.DateTime> v_FECHASERVICIO, Nullable<decimal> v_VALOR, string v_RUTPROF)
        {
            var v_IDSERVParameter = v_IDSERV.HasValue ?
                new ObjectParameter("V_IDSERV", v_IDSERV) :
                new ObjectParameter("V_IDSERV", typeof(decimal));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_FECHASERVICIOParameter = v_FECHASERVICIO.HasValue ?
                new ObjectParameter("V_FECHASERVICIO", v_FECHASERVICIO) :
                new ObjectParameter("V_FECHASERVICIO", typeof(System.DateTime));
    
            var v_VALORParameter = v_VALOR.HasValue ?
                new ObjectParameter("V_VALOR", v_VALOR) :
                new ObjectParameter("V_VALOR", typeof(decimal));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_SERVICIO", v_IDSERVParameter, v_RUTCLIENTParameter, v_DESCRIPCIONParameter, v_FECHASERVICIOParameter, v_VALORParameter, v_RUTPROFParameter);
        }
    
        public virtual int SP_UPDATE_SOLICITUD(Nullable<decimal> v_IDSOLICITUD, Nullable<System.DateTime> v_FECHA, string v_DESCRIPCION, string v_RUTCLIENT, Nullable<decimal> v_IDTIPOSOLICITUD)
        {
            var v_IDSOLICITUDParameter = v_IDSOLICITUD.HasValue ?
                new ObjectParameter("V_IDSOLICITUD", v_IDSOLICITUD) :
                new ObjectParameter("V_IDSOLICITUD", typeof(decimal));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_IDTIPOSOLICITUDParameter = v_IDTIPOSOLICITUD.HasValue ?
                new ObjectParameter("V_IDTIPOSOLICITUD", v_IDTIPOSOLICITUD) :
                new ObjectParameter("V_IDTIPOSOLICITUD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_SOLICITUD", v_IDSOLICITUDParameter, v_FECHAParameter, v_DESCRIPCIONParameter, v_RUTCLIENTParameter, v_IDTIPOSOLICITUDParameter);
        }
    
        public virtual int SP_UPDATE_USUARIOS(Nullable<decimal> v_IDUSER, string v_NOMBRE, string v_PASS, Nullable<decimal> v_ROLID)
        {
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_PASSParameter = v_PASS != null ?
                new ObjectParameter("V_PASS", v_PASS) :
                new ObjectParameter("V_PASS", typeof(string));
    
            var v_ROLIDParameter = v_ROLID.HasValue ?
                new ObjectParameter("V_ROLID", v_ROLID) :
                new ObjectParameter("V_ROLID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_USUARIOS", v_IDUSERParameter, v_NOMBREParameter, v_PASSParameter, v_ROLIDParameter);
        }
    
        public virtual int SP_UPDATE_VISITASTERRENO(Nullable<decimal> v_IDVISITA, Nullable<System.DateTime> v_FECHAVISITA, string v_RUTPROF, string v_RUTCLIENT)
        {
            var v_IDVISITAParameter = v_IDVISITA.HasValue ?
                new ObjectParameter("V_IDVISITA", v_IDVISITA) :
                new ObjectParameter("V_IDVISITA", typeof(decimal));
    
            var v_FECHAVISITAParameter = v_FECHAVISITA.HasValue ?
                new ObjectParameter("V_FECHAVISITA", v_FECHAVISITA) :
                new ObjectParameter("V_FECHAVISITA", typeof(System.DateTime));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_VISITASTERRENO", v_IDVISITAParameter, v_FECHAVISITAParameter, v_RUTPROFParameter, v_RUTCLIENTParameter);
        }
    
        public virtual int SP_CREATE_CAPACITACIONES(Nullable<System.DateTime> v_FECHA, string v_RUTPROFESIONAL, string v_RUTCLIENT, string v_DESCMATERIAL, string v_REALIZADA)
        {
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_RUTPROFESIONALParameter = v_RUTPROFESIONAL != null ?
                new ObjectParameter("V_RUTPROFESIONAL", v_RUTPROFESIONAL) :
                new ObjectParameter("V_RUTPROFESIONAL", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_DESCMATERIALParameter = v_DESCMATERIAL != null ?
                new ObjectParameter("V_DESCMATERIAL", v_DESCMATERIAL) :
                new ObjectParameter("V_DESCMATERIAL", typeof(string));
    
            var v_REALIZADAParameter = v_REALIZADA != null ?
                new ObjectParameter("V_REALIZADA", v_REALIZADA) :
                new ObjectParameter("V_REALIZADA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CAPACITACIONES", v_FECHAParameter, v_RUTPROFESIONALParameter, v_RUTCLIENTParameter, v_DESCMATERIALParameter, v_REALIZADAParameter);
        }
    
        public virtual int SP_CREATE_CHECKLIST(Nullable<decimal> v_VISITATERRENO, string v_STRING01, string v_STRING02, string v_STRING03, string v_STRING04, string v_STRING05, string v_STRING06, string v_STRING07, string v_STRING08, string v_STRING09, string v_STRING10, string v_STRING11, string v_STRING12, string v_STRING13, string v_STRING14, string v_STRING15)
        {
            var v_VISITATERRENOParameter = v_VISITATERRENO.HasValue ?
                new ObjectParameter("V_VISITATERRENO", v_VISITATERRENO) :
                new ObjectParameter("V_VISITATERRENO", typeof(decimal));
    
            var v_STRING01Parameter = v_STRING01 != null ?
                new ObjectParameter("V_STRING01", v_STRING01) :
                new ObjectParameter("V_STRING01", typeof(string));
    
            var v_STRING02Parameter = v_STRING02 != null ?
                new ObjectParameter("V_STRING02", v_STRING02) :
                new ObjectParameter("V_STRING02", typeof(string));
    
            var v_STRING03Parameter = v_STRING03 != null ?
                new ObjectParameter("V_STRING03", v_STRING03) :
                new ObjectParameter("V_STRING03", typeof(string));
    
            var v_STRING04Parameter = v_STRING04 != null ?
                new ObjectParameter("V_STRING04", v_STRING04) :
                new ObjectParameter("V_STRING04", typeof(string));
    
            var v_STRING05Parameter = v_STRING05 != null ?
                new ObjectParameter("V_STRING05", v_STRING05) :
                new ObjectParameter("V_STRING05", typeof(string));
    
            var v_STRING06Parameter = v_STRING06 != null ?
                new ObjectParameter("V_STRING06", v_STRING06) :
                new ObjectParameter("V_STRING06", typeof(string));
    
            var v_STRING07Parameter = v_STRING07 != null ?
                new ObjectParameter("V_STRING07", v_STRING07) :
                new ObjectParameter("V_STRING07", typeof(string));
    
            var v_STRING08Parameter = v_STRING08 != null ?
                new ObjectParameter("V_STRING08", v_STRING08) :
                new ObjectParameter("V_STRING08", typeof(string));
    
            var v_STRING09Parameter = v_STRING09 != null ?
                new ObjectParameter("V_STRING09", v_STRING09) :
                new ObjectParameter("V_STRING09", typeof(string));
    
            var v_STRING10Parameter = v_STRING10 != null ?
                new ObjectParameter("V_STRING10", v_STRING10) :
                new ObjectParameter("V_STRING10", typeof(string));
    
            var v_STRING11Parameter = v_STRING11 != null ?
                new ObjectParameter("V_STRING11", v_STRING11) :
                new ObjectParameter("V_STRING11", typeof(string));
    
            var v_STRING12Parameter = v_STRING12 != null ?
                new ObjectParameter("V_STRING12", v_STRING12) :
                new ObjectParameter("V_STRING12", typeof(string));
    
            var v_STRING13Parameter = v_STRING13 != null ?
                new ObjectParameter("V_STRING13", v_STRING13) :
                new ObjectParameter("V_STRING13", typeof(string));
    
            var v_STRING14Parameter = v_STRING14 != null ?
                new ObjectParameter("V_STRING14", v_STRING14) :
                new ObjectParameter("V_STRING14", typeof(string));
    
            var v_STRING15Parameter = v_STRING15 != null ?
                new ObjectParameter("V_STRING15", v_STRING15) :
                new ObjectParameter("V_STRING15", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CHECKLIST", v_VISITATERRENOParameter, v_STRING01Parameter, v_STRING02Parameter, v_STRING03Parameter, v_STRING04Parameter, v_STRING05Parameter, v_STRING06Parameter, v_STRING07Parameter, v_STRING08Parameter, v_STRING09Parameter, v_STRING10Parameter, v_STRING11Parameter, v_STRING12Parameter, v_STRING13Parameter, v_STRING14Parameter, v_STRING15Parameter);
        }
    
        public virtual int SP_CREATE_HISTORIALATRASOS(Nullable<System.DateTime> v_FECHA, string v_RUTPROF)
        {
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_HISTORIALATRASOS", v_FECHAParameter, v_RUTPROFParameter);
        }
    
        public virtual int SP_UPDATE_CAPACITACIONES(Nullable<decimal> v_IDCAP, Nullable<System.DateTime> v_FECHA, string v_RUTPROFESIONAL, string v_RUTCLIENT, string v_DESCMATERIAL, Nullable<bool> v_REALIZADA)
        {
            var v_IDCAPParameter = v_IDCAP.HasValue ?
                new ObjectParameter("V_IDCAP", v_IDCAP) :
                new ObjectParameter("V_IDCAP", typeof(decimal));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_RUTPROFESIONALParameter = v_RUTPROFESIONAL != null ?
                new ObjectParameter("V_RUTPROFESIONAL", v_RUTPROFESIONAL) :
                new ObjectParameter("V_RUTPROFESIONAL", typeof(string));
    
            var v_RUTCLIENTParameter = v_RUTCLIENT != null ?
                new ObjectParameter("V_RUTCLIENT", v_RUTCLIENT) :
                new ObjectParameter("V_RUTCLIENT", typeof(string));
    
            var v_DESCMATERIALParameter = v_DESCMATERIAL != null ?
                new ObjectParameter("V_DESCMATERIAL", v_DESCMATERIAL) :
                new ObjectParameter("V_DESCMATERIAL", typeof(string));
    
            var v_REALIZADAParameter = v_REALIZADA.HasValue ?
                new ObjectParameter("V_REALIZADA", v_REALIZADA) :
                new ObjectParameter("V_REALIZADA", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CAPACITACIONES", v_IDCAPParameter, v_FECHAParameter, v_RUTPROFESIONALParameter, v_RUTCLIENTParameter, v_DESCMATERIALParameter, v_REALIZADAParameter);
        }
    
        public virtual int SP_UPDATE_CHECKLIST(Nullable<decimal> v_IDCHECKLIST, Nullable<decimal> v_VISITATERRENO, string v_STRING01, string v_STRING02, string v_STRING03, string v_STRING04, string v_STRING05, string v_STRING06, string v_STRING07, string v_STRING08, string v_STRING09, string v_STRING10, string v_STRING11, string v_STRING12, string v_STRING13, string v_STRING14, string v_STRING15)
        {
            var v_IDCHECKLISTParameter = v_IDCHECKLIST.HasValue ?
                new ObjectParameter("V_IDCHECKLIST", v_IDCHECKLIST) :
                new ObjectParameter("V_IDCHECKLIST", typeof(decimal));
    
            var v_VISITATERRENOParameter = v_VISITATERRENO.HasValue ?
                new ObjectParameter("V_VISITATERRENO", v_VISITATERRENO) :
                new ObjectParameter("V_VISITATERRENO", typeof(decimal));
    
            var v_STRING01Parameter = v_STRING01 != null ?
                new ObjectParameter("V_STRING01", v_STRING01) :
                new ObjectParameter("V_STRING01", typeof(string));
    
            var v_STRING02Parameter = v_STRING02 != null ?
                new ObjectParameter("V_STRING02", v_STRING02) :
                new ObjectParameter("V_STRING02", typeof(string));
    
            var v_STRING03Parameter = v_STRING03 != null ?
                new ObjectParameter("V_STRING03", v_STRING03) :
                new ObjectParameter("V_STRING03", typeof(string));
    
            var v_STRING04Parameter = v_STRING04 != null ?
                new ObjectParameter("V_STRING04", v_STRING04) :
                new ObjectParameter("V_STRING04", typeof(string));
    
            var v_STRING05Parameter = v_STRING05 != null ?
                new ObjectParameter("V_STRING05", v_STRING05) :
                new ObjectParameter("V_STRING05", typeof(string));
    
            var v_STRING06Parameter = v_STRING06 != null ?
                new ObjectParameter("V_STRING06", v_STRING06) :
                new ObjectParameter("V_STRING06", typeof(string));
    
            var v_STRING07Parameter = v_STRING07 != null ?
                new ObjectParameter("V_STRING07", v_STRING07) :
                new ObjectParameter("V_STRING07", typeof(string));
    
            var v_STRING08Parameter = v_STRING08 != null ?
                new ObjectParameter("V_STRING08", v_STRING08) :
                new ObjectParameter("V_STRING08", typeof(string));
    
            var v_STRING09Parameter = v_STRING09 != null ?
                new ObjectParameter("V_STRING09", v_STRING09) :
                new ObjectParameter("V_STRING09", typeof(string));
    
            var v_STRING10Parameter = v_STRING10 != null ?
                new ObjectParameter("V_STRING10", v_STRING10) :
                new ObjectParameter("V_STRING10", typeof(string));
    
            var v_STRING11Parameter = v_STRING11 != null ?
                new ObjectParameter("V_STRING11", v_STRING11) :
                new ObjectParameter("V_STRING11", typeof(string));
    
            var v_STRING12Parameter = v_STRING12 != null ?
                new ObjectParameter("V_STRING12", v_STRING12) :
                new ObjectParameter("V_STRING12", typeof(string));
    
            var v_STRING13Parameter = v_STRING13 != null ?
                new ObjectParameter("V_STRING13", v_STRING13) :
                new ObjectParameter("V_STRING13", typeof(string));
    
            var v_STRING14Parameter = v_STRING14 != null ?
                new ObjectParameter("V_STRING14", v_STRING14) :
                new ObjectParameter("V_STRING14", typeof(string));
    
            var v_STRING15Parameter = v_STRING15 != null ?
                new ObjectParameter("V_STRING15", v_STRING15) :
                new ObjectParameter("V_STRING15", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CHECKLIST", v_IDCHECKLISTParameter, v_VISITATERRENOParameter, v_STRING01Parameter, v_STRING02Parameter, v_STRING03Parameter, v_STRING04Parameter, v_STRING05Parameter, v_STRING06Parameter, v_STRING07Parameter, v_STRING08Parameter, v_STRING09Parameter, v_STRING10Parameter, v_STRING11Parameter, v_STRING12Parameter, v_STRING13Parameter, v_STRING14Parameter, v_STRING15Parameter);
        }
    
        public virtual int SP_UPDATE_HISTORIALATRASOS(Nullable<decimal> v_ATRASO, Nullable<System.DateTime> v_FECHA, string v_RUTPROF)
        {
            var v_ATRASOParameter = v_ATRASO.HasValue ?
                new ObjectParameter("V_ATRASO", v_ATRASO) :
                new ObjectParameter("V_ATRASO", typeof(decimal));
    
            var v_FECHAParameter = v_FECHA.HasValue ?
                new ObjectParameter("V_FECHA", v_FECHA) :
                new ObjectParameter("V_FECHA", typeof(System.DateTime));
    
            var v_RUTPROFParameter = v_RUTPROF != null ?
                new ObjectParameter("V_RUTPROF", v_RUTPROF) :
                new ObjectParameter("V_RUTPROF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_HISTORIALATRASOS", v_ATRASOParameter, v_FECHAParameter, v_RUTPROFParameter);
        }
    }
}
