//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public decimal ID_USER { get; set; }
        public string NOMBRE { get; set; }
        public byte[] PASSWORDHASH { get; set; }
        public string SALT { get; set; }
        public short ROL_ID_ROL { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
