<<<<<<< HEAD
<<<<<<< HEAD
-- Generado por Oracle SQL Developer Data Modeler 3.1.1.703
--   en:        2022-11-05 12:33:10 CLST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE SAFECORE.ACTIVIDADMEJORA CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CLIENTES CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CONTRATOCLIENT CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CONTRATOPROF CASCADE CONSTRAINTS 
;
DROP TABLE Capacitaciones CASCADE CONSTRAINTS 
;
DROP TABLE CheckList CASCADE CONSTRAINTS 
;
DROP TABLE HistorialAtrasos CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.PAGOS CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.PROFESIONAL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTEACCIDENTE CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTECLIENTE CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTEGLOBAL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.ROL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.SERVICIO CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.SOLICITUD CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.TIPOSOLICITUD CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.USUARIOS CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.VISITASTERRENO CASCADE CONSTRAINTS 
;
CREATE TABLE SAFECORE.ACTIVIDADMEJORA 
    ( 
     ID_ACTIVIDADMEJORA NUMBER  NOT NULL , 
     NOMBREMEJORA VARCHAR2 (20 BYTE) , 
     DESCRIPCIONMEJORA VARCHAR2 (300 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE)  NOT NULL 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.ACTIVIDADMEJORA_PK ON SAFECORE.ACTIVIDADMEJORA 
    ( 
     ID_ACTIVIDADMEJORA ASC 
    ) 
;

ALTER TABLE SAFECORE.ACTIVIDADMEJORA 
    ADD CONSTRAINT ACTIVIDADMEJORA_PK PRIMARY KEY ( ID_ACTIVIDADMEJORA ) ;



CREATE TABLE SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT CHAR (9 BYTE)  NOT NULL , 
     NOMBRE VARCHAR2 (40 BYTE) , 
     DIRECCION VARCHAR2 (40 BYTE) , 
     TELEFONO VARCHAR2 (13 BYTE) , 
     CORREO VARCHAR2 (50 BYTE) , 
     RUBRO VARCHAR2 (200 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CLIENTES_PK ON SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT ASC 
    ) 
;

ALTER TABLE SAFECORE.CLIENTES 
    ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( RUT_CLIENT ) ;



CREATE TABLE SAFECORE.CONTRATOCLIENT 
    ( 
     ID_CONTR NUMBER (7)  NOT NULL , 
     ACTIVO CHAR (1 BYTE) , 
     FECHAINICIO DATE , 
     FECHATERMINO DATE , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CONTRATOCLIENT_PK ON SAFECORE.CONTRATOCLIENT 
    ( 
     ID_CONTR ASC 
    ) 
;

ALTER TABLE SAFECORE.CONTRATOCLIENT 
    ADD CONSTRAINT CONTRATOCLIENT_PK PRIMARY KEY ( ID_CONTR ) ;



CREATE TABLE SAFECORE.CONTRATOPROF 
    ( 
     ID_CONTR NUMBER  NOT NULL , 
     FECHAINICIO DATE , 
     FECHATERMINO DATE , 
     HISTORIAL VARCHAR2 (300 BYTE) , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CONTRATOPROF_PK ON SAFECORE.CONTRATOPROF 
    ( 
     ID_CONTR ASC 
    ) 
;

ALTER TABLE SAFECORE.CONTRATOPROF 
    ADD CONSTRAINT CONTRATOPROF_PK PRIMARY KEY ( ID_CONTR ) ;



CREATE TABLE Capacitaciones 
    ( 
     ID_Cap NUMBER  NOT NULL , 
     Fecha_realiza DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE)  NOT NULL , 
     Desc_material VARCHAR2 (100) , 
     Realizada CHAR (1) 
    ) 
;



ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_PK PRIMARY KEY ( ID_Cap ) ;



CREATE TABLE CheckList 
    ( 
     ID_check NUMBER  NOT NULL , 
     VISITASTERRENO_ID_VISITA NUMBER (10)  NOT NULL , 
     Field01 VARCHAR2 (100) , 
     Field02 VARCHAR2 (100) , 
     Field03 VARCHAR2 (100) , 
     Field04 VARCHAR2 (100) , 
     Field05 VARCHAR2 (100) , 
     Field06 VARCHAR2 (100) , 
     Field07 VARCHAR2 (100) , 
     Field08 VARCHAR2 (100) , 
     Field09 VARCHAR2 (100) , 
     Field10 VARCHAR2 (100) , 
     Field11 VARCHAR2 (100) , 
     Field12 VARCHAR2 (100) , 
     Field13 VARCHAR2 (100) , 
     Field14 VARCHAR2 (100) , 
     Field15 VARCHAR2 (100) 
    ) 
;



ALTER TABLE CheckList 
    ADD CONSTRAINT CheckList_PK PRIMARY KEY ( ID_check ) ;



CREATE TABLE HistorialAtrasos 
    ( 
     ID_Atraso NUMBER  NOT NULL , 
     Fecha DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE)  NOT NULL 
    ) 
;



ALTER TABLE HistorialAtrasos 
    ADD CONSTRAINT HistorialAtrasos_PK PRIMARY KEY ( ID_Atraso ) ;



CREATE TABLE SAFECORE.PAGOS 
    ( 
     ID_PAGO NUMBER (10)  NOT NULL , 
     FECHA DATE , 
     MONTO NUMBER (9) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.PAGOS_PK ON SAFECORE.PAGOS 
    ( 
     ID_PAGO ASC 
    ) 
;

ALTER TABLE SAFECORE.PAGOS 
    ADD CONSTRAINT PAGOS_PK PRIMARY KEY ( ID_PAGO ) ;



CREATE TABLE SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF CHAR (9 BYTE)  NOT NULL , 
     ACTIVO CHAR (1 BYTE) , 
     NOMBRE VARCHAR2 (100 BYTE) , 
     APELLIDO VARCHAR2 (100 BYTE) , 
     GENERO VARCHAR2 (10 BYTE) , 
     DIRECCION VARCHAR2 (40 BYTE) , 
     TELEFONO VARCHAR2 (13 BYTE) , 
     CORREO VARCHAR2 (50 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.PROFESIONAL_PK ON SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF ASC 
    ) 
;

ALTER TABLE SAFECORE.PROFESIONAL 
    ADD CONSTRAINT PROFESIONAL_PK PRIMARY KEY ( RUT_PROF ) ;



CREATE TABLE SAFECORE.REPORTEACCIDENTE 
    ( 
     ID_REPORTA NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHAACCIDENTE DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTEACCIDENTE_PK ON SAFECORE.REPORTEACCIDENTE 
    ( 
     ID_REPORTA ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTEACCIDENTE 
    ADD CONSTRAINT REPORTEACCIDENTE_PK PRIMARY KEY ( ID_REPORTA ) ;



CREATE TABLE SAFECORE.REPORTECLIENTE 
    ( 
     ID_REPORTC NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTECLIENTE_PK ON SAFECORE.REPORTECLIENTE 
    ( 
     ID_REPORTC ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTECLIENTE 
    ADD CONSTRAINT REPORTECLIENTE_PK PRIMARY KEY ( ID_REPORTC ) ;



CREATE TABLE SAFECORE.REPORTEGLOBAL 
    ( 
     ID_REPORTG NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTEGLOBAL_PK ON SAFECORE.REPORTEGLOBAL 
    ( 
     ID_REPORTG ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTEGLOBAL 
    ADD CONSTRAINT REPORTEGLOBAL_PK PRIMARY KEY ( ID_REPORTG ) ;



CREATE TABLE SAFECORE.ROL 
    ( 
     ID_ROL NUMBER (1)  NOT NULL , 
     NOMBREROL VARCHAR2 (20 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.ROL_PK ON SAFECORE.ROL 
    ( 
     ID_ROL ASC 
    ) 
;

ALTER TABLE SAFECORE.ROL 
    ADD CONSTRAINT ROL_PK PRIMARY KEY ( ID_ROL ) ;



CREATE TABLE SAFECORE.SERVICIO 
    ( 
     ID_SERV NUMBER (7)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     DESCRIPCION VARCHAR2 (300 BYTE) , 
     FECHASERVICIO DATE , 
     VALOR NUMBER (8) , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.SERVICIO_PK ON SAFECORE.SERVICIO 
    ( 
     ID_SERV ASC 
    ) 
;

ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_PK PRIMARY KEY ( ID_SERV ) ;



CREATE TABLE SAFECORE.SOLICITUD 
    ( 
     ID_SOLICITUD NUMBER (8)  NOT NULL , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (300 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     TIPOSOLICITUD_ID_TIPOSOLICITUD NUMBER 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.SOLICITUDASESORIA_PK ON SAFECORE.SOLICITUD 
    ( 
     ID_SOLICITUD ASC 
    ) 
;

ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUDASESORIA_PK PRIMARY KEY ( ID_SOLICITUD ) ;



CREATE TABLE SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD NUMBER  NOT NULL , 
     TIPOSOLICITUD VARCHAR2 (10 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.TIPOSOLICITUD_PK ON SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD ASC 
    ) 
;

ALTER TABLE SAFECORE.TIPOSOLICITUD 
    ADD CONSTRAINT TIPOSOLICITUD_PK PRIMARY KEY ( ID_TIPOSOLICITUD ) ;



CREATE TABLE SAFECORE.USUARIOS 
    ( 
     ID_USER NUMBER  NOT NULL , 
     NOMBRE VARCHAR2 (200 BYTE) , 
     ROL_ID_ROL NUMBER (1) , 
     PASS VARCHAR2 (32 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.USUARIOS_PK ON SAFECORE.USUARIOS 
    ( 
     ID_USER ASC 
    ) 
;

ALTER TABLE SAFECORE.USUARIOS 
    ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( ID_USER ) ;



CREATE TABLE SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA NUMBER (10)  NOT NULL , 
     FECHAVISITA DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.VISITASTERRENO_PK ON SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA ASC 
    ) 
;

ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_PK PRIMARY KEY ( ID_VISITA ) ;




ALTER TABLE SAFECORE.ACTIVIDADMEJORA 
    ADD CONSTRAINT ACTIVIDADMEJORA_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE HistorialAtrasos 
    ADD CONSTRAINT Atrasos_PROF_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE SAFECORE.CONTRATOCLIENT 
    ADD CONSTRAINT CONTRATOCLIENT_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.CONTRATOPROF 
    ADD CONSTRAINT CONTRATOPROF_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE CheckList 
    ADD CONSTRAINT CheckList_VISITASTERRENO_FK FOREIGN KEY 
    ( 
     VISITASTERRENO_ID_VISITA
    ) 
    REFERENCES SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA
    ) 
;


ALTER TABLE SAFECORE.PAGOS 
    ADD CONSTRAINT PAGOS_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTEACCIDENTE 
    ADD CONSTRAINT REPORTEACCIDENTE_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTECLIENTE 
    ADD CONSTRAINT REPORTECLIENTE_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTEGLOBAL 
    ADD CONSTRAINT REPORTEGLOBAL_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUDASESORIA_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUD_TIPOSOLICITUD_FK FOREIGN KEY 
    ( 
     TIPOSOLICITUD_ID_TIPOSOLICITUD
    ) 
    REFERENCES SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD
    ) 
;


ALTER TABLE SAFECORE.USUARIOS 
    ADD CONSTRAINT USUARIOS_ROL_FK FOREIGN KEY 
    ( 
     ROL_ID_ROL
    ) 
    REFERENCES SAFECORE.ROL 
    ( 
     ID_ROL
    ) 
;


ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                            15
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
=======
-- Generado por Oracle SQL Developer Data Modeler 3.1.1.703
--   en:        2022-11-05 12:33:10 CLST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE SAFECORE.ACTIVIDADMEJORA CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CLIENTES CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CONTRATOCLIENT CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CONTRATOPROF CASCADE CONSTRAINTS 
;
DROP TABLE Capacitaciones CASCADE CONSTRAINTS 
;
DROP TABLE CheckList CASCADE CONSTRAINTS 
;
DROP TABLE HistorialAtrasos CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.PAGOS CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.PROFESIONAL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTEACCIDENTE CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTECLIENTE CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTEGLOBAL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.ROL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.SERVICIO CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.SOLICITUD CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.TIPOSOLICITUD CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.USUARIOS CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.VISITASTERRENO CASCADE CONSTRAINTS 
;
CREATE TABLE SAFECORE.ACTIVIDADMEJORA 
    ( 
     ID_ACTIVIDADMEJORA NUMBER  NOT NULL , 
     NOMBREMEJORA VARCHAR2 (20 BYTE) , 
     DESCRIPCIONMEJORA VARCHAR2 (300 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE)  NOT NULL 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.ACTIVIDADMEJORA_PK ON SAFECORE.ACTIVIDADMEJORA 
    ( 
     ID_ACTIVIDADMEJORA ASC 
    ) 
;

ALTER TABLE SAFECORE.ACTIVIDADMEJORA 
    ADD CONSTRAINT ACTIVIDADMEJORA_PK PRIMARY KEY ( ID_ACTIVIDADMEJORA ) ;



CREATE TABLE SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT CHAR (9 BYTE)  NOT NULL , 
     NOMBRE VARCHAR2 (40 BYTE) , 
     DIRECCION VARCHAR2 (40 BYTE) , 
     TELEFONO VARCHAR2 (13 BYTE) , 
     CORREO VARCHAR2 (50 BYTE) , 
     RUBRO VARCHAR2 (200 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CLIENTES_PK ON SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT ASC 
    ) 
;

ALTER TABLE SAFECORE.CLIENTES 
    ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( RUT_CLIENT ) ;



CREATE TABLE SAFECORE.CONTRATOCLIENT 
    ( 
     ID_CONTR NUMBER (7)  NOT NULL , 
     ACTIVO CHAR (1 BYTE) , 
     FECHAINICIO DATE , 
     FECHATERMINO DATE , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CONTRATOCLIENT_PK ON SAFECORE.CONTRATOCLIENT 
    ( 
     ID_CONTR ASC 
    ) 
;

ALTER TABLE SAFECORE.CONTRATOCLIENT 
    ADD CONSTRAINT CONTRATOCLIENT_PK PRIMARY KEY ( ID_CONTR ) ;



CREATE TABLE SAFECORE.CONTRATOPROF 
    ( 
     ID_CONTR NUMBER  NOT NULL , 
     FECHAINICIO DATE , 
     FECHATERMINO DATE , 
     HISTORIAL VARCHAR2 (300 BYTE) , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CONTRATOPROF_PK ON SAFECORE.CONTRATOPROF 
    ( 
     ID_CONTR ASC 
    ) 
;

ALTER TABLE SAFECORE.CONTRATOPROF 
    ADD CONSTRAINT CONTRATOPROF_PK PRIMARY KEY ( ID_CONTR ) ;



CREATE TABLE Capacitaciones 
    ( 
     ID_Cap NUMBER  NOT NULL , 
     Fecha_realiza DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE)  NOT NULL , 
     Desc_material VARCHAR2 (100) , 
     Realizada CHAR (1) 
    ) 
;



ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_PK PRIMARY KEY ( ID_Cap ) ;



CREATE TABLE CheckList 
    ( 
     ID_check NUMBER  NOT NULL , 
     VISITASTERRENO_ID_VISITA NUMBER (10)  NOT NULL , 
     Field01 VARCHAR2 (100) , 
     Field02 VARCHAR2 (100) , 
     Field03 VARCHAR2 (100) , 
     Field04 VARCHAR2 (100) , 
     Field05 VARCHAR2 (100) , 
     Field06 VARCHAR2 (100) , 
     Field07 VARCHAR2 (100) , 
     Field08 VARCHAR2 (100) , 
     Field09 VARCHAR2 (100) , 
     Field10 VARCHAR2 (100) , 
     Field11 VARCHAR2 (100) , 
     Field12 VARCHAR2 (100) , 
     Field13 VARCHAR2 (100) , 
     Field14 VARCHAR2 (100) , 
     Field15 VARCHAR2 (100) 
    ) 
;



ALTER TABLE CheckList 
    ADD CONSTRAINT CheckList_PK PRIMARY KEY ( ID_check ) ;



CREATE TABLE HistorialAtrasos 
    ( 
     ID_Atraso NUMBER  NOT NULL , 
     Fecha DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE)  NOT NULL 
    ) 
;



ALTER TABLE HistorialAtrasos 
    ADD CONSTRAINT HistorialAtrasos_PK PRIMARY KEY ( ID_Atraso ) ;



CREATE TABLE SAFECORE.PAGOS 
    ( 
     ID_PAGO NUMBER (10)  NOT NULL , 
     FECHA DATE , 
     MONTO NUMBER (9) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.PAGOS_PK ON SAFECORE.PAGOS 
    ( 
     ID_PAGO ASC 
    ) 
;

ALTER TABLE SAFECORE.PAGOS 
    ADD CONSTRAINT PAGOS_PK PRIMARY KEY ( ID_PAGO ) ;



CREATE TABLE SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF CHAR (9 BYTE)  NOT NULL , 
     ACTIVO CHAR (1 BYTE) , 
     NOMBRE VARCHAR2 (100 BYTE) , 
     APELLIDO VARCHAR2 (100 BYTE) , 
     GENERO VARCHAR2 (10 BYTE) , 
     DIRECCION VARCHAR2 (40 BYTE) , 
     TELEFONO VARCHAR2 (13 BYTE) , 
     CORREO VARCHAR2 (50 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.PROFESIONAL_PK ON SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF ASC 
    ) 
;

ALTER TABLE SAFECORE.PROFESIONAL 
    ADD CONSTRAINT PROFESIONAL_PK PRIMARY KEY ( RUT_PROF ) ;



CREATE TABLE SAFECORE.REPORTEACCIDENTE 
    ( 
     ID_REPORTA NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHAACCIDENTE DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTEACCIDENTE_PK ON SAFECORE.REPORTEACCIDENTE 
    ( 
     ID_REPORTA ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTEACCIDENTE 
    ADD CONSTRAINT REPORTEACCIDENTE_PK PRIMARY KEY ( ID_REPORTA ) ;



CREATE TABLE SAFECORE.REPORTECLIENTE 
    ( 
     ID_REPORTC NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTECLIENTE_PK ON SAFECORE.REPORTECLIENTE 
    ( 
     ID_REPORTC ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTECLIENTE 
    ADD CONSTRAINT REPORTECLIENTE_PK PRIMARY KEY ( ID_REPORTC ) ;



CREATE TABLE SAFECORE.REPORTEGLOBAL 
    ( 
     ID_REPORTG NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTEGLOBAL_PK ON SAFECORE.REPORTEGLOBAL 
    ( 
     ID_REPORTG ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTEGLOBAL 
    ADD CONSTRAINT REPORTEGLOBAL_PK PRIMARY KEY ( ID_REPORTG ) ;



CREATE TABLE SAFECORE.ROL 
    ( 
     ID_ROL NUMBER (1)  NOT NULL , 
     NOMBREROL VARCHAR2 (20 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.ROL_PK ON SAFECORE.ROL 
    ( 
     ID_ROL ASC 
    ) 
;

ALTER TABLE SAFECORE.ROL 
    ADD CONSTRAINT ROL_PK PRIMARY KEY ( ID_ROL ) ;



CREATE TABLE SAFECORE.SERVICIO 
    ( 
     ID_SERV NUMBER (7)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     DESCRIPCION VARCHAR2 (300 BYTE) , 
     FECHASERVICIO DATE , 
     VALOR NUMBER (8) , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.SERVICIO_PK ON SAFECORE.SERVICIO 
    ( 
     ID_SERV ASC 
    ) 
;

ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_PK PRIMARY KEY ( ID_SERV ) ;



CREATE TABLE SAFECORE.SOLICITUD 
    ( 
     ID_SOLICITUD NUMBER (8)  NOT NULL , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (300 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     TIPOSOLICITUD_ID_TIPOSOLICITUD NUMBER 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.SOLICITUDASESORIA_PK ON SAFECORE.SOLICITUD 
    ( 
     ID_SOLICITUD ASC 
    ) 
;

ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUDASESORIA_PK PRIMARY KEY ( ID_SOLICITUD ) ;



CREATE TABLE SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD NUMBER  NOT NULL , 
     TIPOSOLICITUD VARCHAR2 (10 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.TIPOSOLICITUD_PK ON SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD ASC 
    ) 
;

ALTER TABLE SAFECORE.TIPOSOLICITUD 
    ADD CONSTRAINT TIPOSOLICITUD_PK PRIMARY KEY ( ID_TIPOSOLICITUD ) ;



CREATE TABLE SAFECORE.USUARIOS 
    ( 
     ID_USER NUMBER  NOT NULL , 
     NOMBRE VARCHAR2 (200 BYTE) , 
     ROL_ID_ROL NUMBER (1) , 
     PASS VARCHAR2 (32 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.USUARIOS_PK ON SAFECORE.USUARIOS 
    ( 
     ID_USER ASC 
    ) 
;

ALTER TABLE SAFECORE.USUARIOS 
    ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( ID_USER ) ;



CREATE TABLE SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA NUMBER (10)  NOT NULL , 
     FECHAVISITA DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.VISITASTERRENO_PK ON SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA ASC 
    ) 
;

ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_PK PRIMARY KEY ( ID_VISITA ) ;




ALTER TABLE SAFECORE.ACTIVIDADMEJORA 
    ADD CONSTRAINT ACTIVIDADMEJORA_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE HistorialAtrasos 
    ADD CONSTRAINT Atrasos_PROF_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE SAFECORE.CONTRATOCLIENT 
    ADD CONSTRAINT CONTRATOCLIENT_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.CONTRATOPROF 
    ADD CONSTRAINT CONTRATOPROF_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE CheckList 
    ADD CONSTRAINT CheckList_VISITASTERRENO_FK FOREIGN KEY 
    ( 
     VISITASTERRENO_ID_VISITA
    ) 
    REFERENCES SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA
    ) 
;


ALTER TABLE SAFECORE.PAGOS 
    ADD CONSTRAINT PAGOS_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTEACCIDENTE 
    ADD CONSTRAINT REPORTEACCIDENTE_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTECLIENTE 
    ADD CONSTRAINT REPORTECLIENTE_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTEGLOBAL 
    ADD CONSTRAINT REPORTEGLOBAL_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUDASESORIA_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUD_TIPOSOLICITUD_FK FOREIGN KEY 
    ( 
     TIPOSOLICITUD_ID_TIPOSOLICITUD
    ) 
    REFERENCES SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD
    ) 
;


ALTER TABLE SAFECORE.USUARIOS 
    ADD CONSTRAINT USUARIOS_ROL_FK FOREIGN KEY 
    ( 
     ROL_ID_ROL
    ) 
    REFERENCES SAFECORE.ROL 
    ( 
     ID_ROL
    ) 
;


ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                            15
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
>>>>>>> 2c76cb24d12e03359fc26cacb2ed2d803a32541e
=======
-- Generado por Oracle SQL Developer Data Modeler 3.1.1.703
--   en:        2022-11-05 12:33:10 CLST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE SAFECORE.ACTIVIDADMEJORA CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CLIENTES CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CONTRATOCLIENT CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.CONTRATOPROF CASCADE CONSTRAINTS 
;
DROP TABLE Capacitaciones CASCADE CONSTRAINTS 
;
DROP TABLE CheckList CASCADE CONSTRAINTS 
;
DROP TABLE HistorialAtrasos CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.PAGOS CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.PROFESIONAL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTEACCIDENTE CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTECLIENTE CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.REPORTEGLOBAL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.ROL CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.SERVICIO CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.SOLICITUD CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.TIPOSOLICITUD CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.USUARIOS CASCADE CONSTRAINTS 
;
DROP TABLE SAFECORE.VISITASTERRENO CASCADE CONSTRAINTS 
;
CREATE TABLE SAFECORE.ACTIVIDADMEJORA 
    ( 
     ID_ACTIVIDADMEJORA NUMBER  NOT NULL , 
     NOMBREMEJORA VARCHAR2 (20 BYTE) , 
     DESCRIPCIONMEJORA VARCHAR2 (300 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE)  NOT NULL 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.ACTIVIDADMEJORA_PK ON SAFECORE.ACTIVIDADMEJORA 
    ( 
     ID_ACTIVIDADMEJORA ASC 
    ) 
;

ALTER TABLE SAFECORE.ACTIVIDADMEJORA 
    ADD CONSTRAINT ACTIVIDADMEJORA_PK PRIMARY KEY ( ID_ACTIVIDADMEJORA ) ;



CREATE TABLE SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT CHAR (9 BYTE)  NOT NULL , 
     NOMBRE VARCHAR2 (40 BYTE) , 
     DIRECCION VARCHAR2 (40 BYTE) , 
     TELEFONO VARCHAR2 (13 BYTE) , 
     CORREO VARCHAR2 (50 BYTE) , 
     RUBRO VARCHAR2 (200 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CLIENTES_PK ON SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT ASC 
    ) 
;

ALTER TABLE SAFECORE.CLIENTES 
    ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( RUT_CLIENT ) ;



CREATE TABLE SAFECORE.CONTRATOCLIENT 
    ( 
     ID_CONTR NUMBER (7)  NOT NULL , 
     ACTIVO CHAR (1 BYTE) , 
     FECHAINICIO DATE , 
     FECHATERMINO DATE , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CONTRATOCLIENT_PK ON SAFECORE.CONTRATOCLIENT 
    ( 
     ID_CONTR ASC 
    ) 
;

ALTER TABLE SAFECORE.CONTRATOCLIENT 
    ADD CONSTRAINT CONTRATOCLIENT_PK PRIMARY KEY ( ID_CONTR ) ;



CREATE TABLE SAFECORE.CONTRATOPROF 
    ( 
     ID_CONTR NUMBER  NOT NULL , 
     FECHAINICIO DATE , 
     FECHATERMINO DATE , 
     HISTORIAL VARCHAR2 (300 BYTE) , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.CONTRATOPROF_PK ON SAFECORE.CONTRATOPROF 
    ( 
     ID_CONTR ASC 
    ) 
;

ALTER TABLE SAFECORE.CONTRATOPROF 
    ADD CONSTRAINT CONTRATOPROF_PK PRIMARY KEY ( ID_CONTR ) ;



CREATE TABLE Capacitaciones 
    ( 
     ID_Cap NUMBER  NOT NULL , 
     Fecha_realiza DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE)  NOT NULL , 
     Desc_material VARCHAR2 (100) , 
     Realizada CHAR (1) 
    ) 
;



ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_PK PRIMARY KEY ( ID_Cap ) ;



CREATE TABLE CheckList 
    ( 
     ID_check NUMBER  NOT NULL , 
     VISITASTERRENO_ID_VISITA NUMBER (10)  NOT NULL , 
     Field01 VARCHAR2 (100) , 
     Field02 VARCHAR2 (100) , 
     Field03 VARCHAR2 (100) , 
     Field04 VARCHAR2 (100) , 
     Field05 VARCHAR2 (100) , 
     Field06 VARCHAR2 (100) , 
     Field07 VARCHAR2 (100) , 
     Field08 VARCHAR2 (100) , 
     Field09 VARCHAR2 (100) , 
     Field10 VARCHAR2 (100) , 
     Field11 VARCHAR2 (100) , 
     Field12 VARCHAR2 (100) , 
     Field13 VARCHAR2 (100) , 
     Field14 VARCHAR2 (100) , 
     Field15 VARCHAR2 (100) 
    ) 
;



ALTER TABLE CheckList 
    ADD CONSTRAINT CheckList_PK PRIMARY KEY ( ID_check ) ;



CREATE TABLE HistorialAtrasos 
    ( 
     ID_Atraso NUMBER  NOT NULL , 
     Fecha DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE)  NOT NULL 
    ) 
;



ALTER TABLE HistorialAtrasos 
    ADD CONSTRAINT HistorialAtrasos_PK PRIMARY KEY ( ID_Atraso ) ;



CREATE TABLE SAFECORE.PAGOS 
    ( 
     ID_PAGO NUMBER (10)  NOT NULL , 
     FECHA DATE , 
     MONTO NUMBER (9) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.PAGOS_PK ON SAFECORE.PAGOS 
    ( 
     ID_PAGO ASC 
    ) 
;

ALTER TABLE SAFECORE.PAGOS 
    ADD CONSTRAINT PAGOS_PK PRIMARY KEY ( ID_PAGO ) ;



CREATE TABLE SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF CHAR (9 BYTE)  NOT NULL , 
     ACTIVO CHAR (1 BYTE) , 
     NOMBRE VARCHAR2 (100 BYTE) , 
     APELLIDO VARCHAR2 (100 BYTE) , 
     GENERO VARCHAR2 (10 BYTE) , 
     DIRECCION VARCHAR2 (40 BYTE) , 
     TELEFONO VARCHAR2 (13 BYTE) , 
     CORREO VARCHAR2 (50 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.PROFESIONAL_PK ON SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF ASC 
    ) 
;

ALTER TABLE SAFECORE.PROFESIONAL 
    ADD CONSTRAINT PROFESIONAL_PK PRIMARY KEY ( RUT_PROF ) ;



CREATE TABLE SAFECORE.REPORTEACCIDENTE 
    ( 
     ID_REPORTA NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHAACCIDENTE DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTEACCIDENTE_PK ON SAFECORE.REPORTEACCIDENTE 
    ( 
     ID_REPORTA ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTEACCIDENTE 
    ADD CONSTRAINT REPORTEACCIDENTE_PK PRIMARY KEY ( ID_REPORTA ) ;



CREATE TABLE SAFECORE.REPORTECLIENTE 
    ( 
     ID_REPORTC NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTECLIENTE_PK ON SAFECORE.REPORTECLIENTE 
    ( 
     ID_REPORTC ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTECLIENTE 
    ADD CONSTRAINT REPORTECLIENTE_PK PRIMARY KEY ( ID_REPORTC ) ;



CREATE TABLE SAFECORE.REPORTEGLOBAL 
    ( 
     ID_REPORTG NUMBER (10)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (3000 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.REPORTEGLOBAL_PK ON SAFECORE.REPORTEGLOBAL 
    ( 
     ID_REPORTG ASC 
    ) 
;

ALTER TABLE SAFECORE.REPORTEGLOBAL 
    ADD CONSTRAINT REPORTEGLOBAL_PK PRIMARY KEY ( ID_REPORTG ) ;



CREATE TABLE SAFECORE.ROL 
    ( 
     ID_ROL NUMBER (1)  NOT NULL , 
     NOMBREROL VARCHAR2 (20 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.ROL_PK ON SAFECORE.ROL 
    ( 
     ID_ROL ASC 
    ) 
;

ALTER TABLE SAFECORE.ROL 
    ADD CONSTRAINT ROL_PK PRIMARY KEY ( ID_ROL ) ;



CREATE TABLE SAFECORE.SERVICIO 
    ( 
     ID_SERV NUMBER (7)  NOT NULL , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     DESCRIPCION VARCHAR2 (300 BYTE) , 
     FECHASERVICIO DATE , 
     VALOR NUMBER (8) , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.SERVICIO_PK ON SAFECORE.SERVICIO 
    ( 
     ID_SERV ASC 
    ) 
;

ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_PK PRIMARY KEY ( ID_SERV ) ;



CREATE TABLE SAFECORE.SOLICITUD 
    ( 
     ID_SOLICITUD NUMBER (8)  NOT NULL , 
     FECHA DATE , 
     DESCRIPCION VARCHAR2 (300 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) , 
     TIPOSOLICITUD_ID_TIPOSOLICITUD NUMBER 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.SOLICITUDASESORIA_PK ON SAFECORE.SOLICITUD 
    ( 
     ID_SOLICITUD ASC 
    ) 
;

ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUDASESORIA_PK PRIMARY KEY ( ID_SOLICITUD ) ;



CREATE TABLE SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD NUMBER  NOT NULL , 
     TIPOSOLICITUD VARCHAR2 (10 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.TIPOSOLICITUD_PK ON SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD ASC 
    ) 
;

ALTER TABLE SAFECORE.TIPOSOLICITUD 
    ADD CONSTRAINT TIPOSOLICITUD_PK PRIMARY KEY ( ID_TIPOSOLICITUD ) ;



CREATE TABLE SAFECORE.USUARIOS 
    ( 
     ID_USER NUMBER  NOT NULL , 
     NOMBRE VARCHAR2 (200 BYTE) , 
     ROL_ID_ROL NUMBER (1) , 
     PASS VARCHAR2 (32 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.USUARIOS_PK ON SAFECORE.USUARIOS 
    ( 
     ID_USER ASC 
    ) 
;

ALTER TABLE SAFECORE.USUARIOS 
    ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( ID_USER ) ;



CREATE TABLE SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA NUMBER (10)  NOT NULL , 
     FECHAVISITA DATE , 
     PROFESIONAL_RUT_PROF CHAR (9 BYTE) , 
     CLIENTES_RUT_CLIENT CHAR (9 BYTE) 
    ) 
;


CREATE UNIQUE INDEX SAFECORE.VISITASTERRENO_PK ON SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA ASC 
    ) 
;

ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_PK PRIMARY KEY ( ID_VISITA ) ;




ALTER TABLE SAFECORE.ACTIVIDADMEJORA 
    ADD CONSTRAINT ACTIVIDADMEJORA_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE HistorialAtrasos 
    ADD CONSTRAINT Atrasos_PROF_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE SAFECORE.CONTRATOCLIENT 
    ADD CONSTRAINT CONTRATOCLIENT_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.CONTRATOPROF 
    ADD CONSTRAINT CONTRATOPROF_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE Capacitaciones 
    ADD CONSTRAINT Capacitaciones_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE CheckList 
    ADD CONSTRAINT CheckList_VISITASTERRENO_FK FOREIGN KEY 
    ( 
     VISITASTERRENO_ID_VISITA
    ) 
    REFERENCES SAFECORE.VISITASTERRENO 
    ( 
     ID_VISITA
    ) 
;


ALTER TABLE SAFECORE.PAGOS 
    ADD CONSTRAINT PAGOS_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTEACCIDENTE 
    ADD CONSTRAINT REPORTEACCIDENTE_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTECLIENTE 
    ADD CONSTRAINT REPORTECLIENTE_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.REPORTEGLOBAL 
    ADD CONSTRAINT REPORTEGLOBAL_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SERVICIO 
    ADD CONSTRAINT SERVICIO_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;


ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUDASESORIA_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.SOLICITUD 
    ADD CONSTRAINT SOLICITUD_TIPOSOLICITUD_FK FOREIGN KEY 
    ( 
     TIPOSOLICITUD_ID_TIPOSOLICITUD
    ) 
    REFERENCES SAFECORE.TIPOSOLICITUD 
    ( 
     ID_TIPOSOLICITUD
    ) 
;


ALTER TABLE SAFECORE.USUARIOS 
    ADD CONSTRAINT USUARIOS_ROL_FK FOREIGN KEY 
    ( 
     ROL_ID_ROL
    ) 
    REFERENCES SAFECORE.ROL 
    ( 
     ID_ROL
    ) 
;


ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_RUT_CLIENT
    ) 
    REFERENCES SAFECORE.CLIENTES 
    ( 
     RUT_CLIENT
    ) 
;


ALTER TABLE SAFECORE.VISITASTERRENO 
    ADD CONSTRAINT VISITASTERRENO_PROFESIONAL_FK FOREIGN KEY 
    ( 
     PROFESIONAL_RUT_PROF
    ) 
    REFERENCES SAFECORE.PROFESIONAL 
    ( 
     RUT_PROF
    ) 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                            15
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
>>>>>>> 2c76cb24d12e03359fc26cacb2ed2d803a32541e
